#!/bin/sh
'''exec' "/Users/animeethghosh/Downloads/contentops-ai(ET)Animeeth Ghosh/venv/bin/python3" "$0" "$@"
' '''
import sys
from openai.cli import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
